# program code
code:
  build: docker/code
  env_file: ./code/.env
  volumes:
    - ./code:/code

# database
db:
  build: docker/db
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app_db
    MYSQL_USER: app_db_user
    MYSQL_PASSWORD: app_db_pass

db_test:
  build: docker/db
  volumes:
    - /var/lib/mysql
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: app_db_test
    MYSQL_USER: app_db_user_test
    MYSQL_PASSWORD: app_db_pass_test

## web server
server:
  build: docker/server
  ports:
    - "8080:80"
  volumes_from:
    - code

# program code
vendor:
  build: docker/vendor
  volumes:
    - ./code:/code