app:
  build: docker/php
  dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - ./:/app
  expose:
    - 9000

nginx:
  image: nginx:latest
  expose:
    - 80
  volumes:
    - ./:/app
#    - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
  links:
    - app
