# application code
app:
  entrypoint: tail -f /dev/null
  env_file: ./app/.env
  image: busybox:latest
  volumes:
    - ./app:/var/www/html
  volumn_from:
    - vendor

# web server
server:
  build: docker/server
  ports:
    - "8080:80"
  volumes_from:
    - app
  working_dir: /var/www/html

## vendor packages
vendor:
  build: docker/vendor
